version: '3.3'

services:
  # PostgreSQL service
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - synapse_default
    container_name: postgres_container

  # Django service
  django:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: django_postgis_app
    privileged: true
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENCAGE_API=10a9e27df30d48b9bf5ca88ad1f4ad44
      # fractal database configuration
      - MATRIX_HOMESERVER_URL=http://synapse:8008
      - MATRIX_ACCESS_TOKEN=syt_YWRtaW4_eTZcUyRFMLNowjZNOzlt_1UOWT3
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"
      - "5037:5037"

    networks:
      - synapse_default
    volumes:
      - ./backend:/app  # Mount your project directory to the /app directory in the container
      # - /dev/bus/usb:/dev/bus/usb
    container_name: django_container

  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: react_frontend_app
    environment:
      - REACT_APP_URL=http://django:8000/
    ports:
      - "3000:3000"
    networks:
      - synapse_default
    volumes:
      - ./frontend:/app/frontend/
    depends_on:
      - django
    container_name: react_container


 # RabbitMQ service
  # Redis service
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - synapse_default
    container_name: rabbitmq_container


networks:
  synapse_default:
    external: true

# networks:
#   mynetwork:
#     driver: bridge
