# Generated by Django 5.0.1 on 2024-01-26 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0008_servicearea_delete_customerpolygon_delete_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='object_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
