# Generated by Django 5.0.1 on 2024-01-25 22:10

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertapp', '0003_remove_alertservicemodel_service_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alertservicemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 25, 22, 6, 21, 549677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='object_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 25, 22, 6, 36, 580421, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='object_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
